export const blushes = [
  {
    "name":"Bubblegum",
    "src":"/images/products/blush-bubblegum.png",
    "price":"18.00",
    "category":"blush"
  },
  {
    "name":"Coral",
    "src":"/images/products/blush-coral.png",
    "price":"18.00",
    "category":"blush"
  },
  {
    "name":"Crepe",
    "src":"/images/products/blush-crepe.png",
    "price":"18.00",
    "category":"blush"
  },
  {
    "name":"Peach",
    "src":"/images/products/blush-peach.png",
    "price":"18.00",
    "category":"blush"
  },
  {
    "name":"Rosy",
    "src":"/images/products/blush-rosy.png",
    "price":"18.00",
    "category":"blush"
  },
  {
    "name":"Strawberry",
    "src":"/images/products/blush-strawberry.png",
    "price":"18.00",
    "category":"blush"
  },
  {
    "name":"Tan",
    "src":"/images/products/blush-tan.png",
    "price":"18.00",
    "category":"blush"
  }
];

export const lipsticks = [
  {
    "name":"Bubblegum",
    "src":"/images/products/lipstick-bubblegum.png",
    "price":"15",
    "category":"lipstick"
  },
  {
    "name":"Coral",
    "src":"/images/products/lipstick-coral.png",
    "price":"15",
    "category":"lipstick"
  },
  {
    "name":"Crepe",
    "src":"/images/products/lipstick-crepe.png",
    "price":"15",
    "category":"lipstick"
  },
  {
    "name":"Hot Pink",
    "src":"/images/products/lipstick-hotpink.png",
    "price":"15",
    "category":"lipstick"
  },
  {
    "name":"Nude",
    "src":"/images/products/lipstick-nude.png",
    "price":"15",
    "category":"lipstick"
  },
  {
    "name":"Rose",
    "src":"/images/products/lipstick-rose.png",
    "price":"15",
    "category":"lipstick"
  },
  {
    "name":"Rosewood",
    "src":"/images/products/lipstick-rosewood.png",
    "price":"15",
    "category":"lipstick"
  },
  {
    "name":"Salmon",
    "src":"/images/products/lipstick-salmon.png",
    "price":"15",
    "category":"lipstick"
  },
  {
    "name":"Strawberry",
    "src":"/images/products/lipstick-strawberry.png",
    "price":"",
    "category":"lipstick"
  },
  {
    "name":"Tan",
    "src":"/images/products/lipstick-tan.png",
    "price":"15",
    "category":"lipstick"
  }
];

export const eyeshadows = [
  {
    "name":"Blush",
    "src":"/images/products/eyeshadow-blush.png",
    "price":"17",
    "category":"eyeshadow"
  },
  {
    "name":"Burgundy",
    "src":"/images/products/eyeshadow-burgundy.png",
    "price":"17",
    "category":"eyeshadow"
  },
  {
    "name":"Nude",
    "src":"/images/products/eyeshadow-nude.png",
    "price":"17",
    "category":"eyeshadow"
  }
];